### ISSUE TITLE
Document release procedure

### ISSUE THREAD

**Issue by ericonr** [cnpem/epics-in-docker#17]
Release procedure includes things such as:

- the release commit, which changes version in the IOC `Dockerfile`
- a followup commit, which changes version to `v...-git` (can be merged only after some other functional change is merged)

**Comment by henriquesimoes** [comment]
I don't recall if we defined it to be `-git` or `-dev`. I'd rather have it named `-dev` to make it clear it is not indented for deployment. I'm not sure if `-git` conveys this meaning (after all, everything is managed through Git).

In addition, `-dev` gets a bit closer to other versioning schemes, such as [the one from `setuptools-scm`](https://pypi.org/project/setuptools-scm/#default-versioning-scheme).
