### ISSUE TITLE
Add OPC-UA and ether_ip modules

### ISSUE THREAD

**Issue by ericonr** [cnpem/epics-in-docker#32]
The OPC-UA module will be the pre-built release version built for Debian 11.

**Comment by henriquesimoes** [comment]
#57 partially resolves this issue. Does [`ether_ip`](https://github.com/epics-modules/ether_ip) have anything to do with OPC-UA in the end? Should we add them together?

**Comment by ericonr** [comment]
They are both used in the DELTA undulator IOC, that was why I initially opened this issue :)

**Comment by ericonr** [comment]
Closed by #57
