### ISSUE TITLE
Busybox netcat doesn't support connecting to UNIX sockets, but is found before netcat-openbsd

### ISSUE THREAD

**Issue by ericonr** [cnpem/epics-in-docker#87]
#72 made it necessary to call `docker exec -ti container nc.openbsd -U ioc.sock` to access an iocsh launched by  `lnls-run`, because using `nc` instead uses the busybox version, which doesn't work.

I would consider reverting the commit (almost) entirely and using `busybox wget` in the download step; otherwise we'd have to cleanup some specific part of `busybox --install`.

**Comment by henriquesimoes** [comment]
Yeah, my bad. I should've tested with `lnls-run`, and that way of connecting with the socket.

> I would consider reverting the commit (almost) entirely and using busybox wget in the download step; otherwise we'd have to cleanup some specific part of busybox --install.

Okay. Makes sense. Symbolic linking those that have all features we expect them to have is still desired in the end? If not, I'd be okay to rather document that users have busybox available in resulting images, and that they are encouraged to check its built-in commands before attempting to install any extra package.

**Comment by ericonr** [comment]
No worries :)

> Symbolic linking those that have all features we expect them to have is still desired in the end?

I think so. It is useful, and helps a different use case from mine. We could do `unlink /path/to/busybox/nc`; or document that accessing the iocsh requires `nc.openbsd` (I don't like this option).

**Comment by henriquesimoes** [comment]
> We could do unlink `/path/to/busybox/nc`;

I'll try that one.

> or document that accessing the iocsh requires `nc.openbsd` (I don't like this option).

Neither do I.

**Comment by henriquesimoes** [comment]
Okay. That's more interesting than I thought. Things are broken due to `/bin` and `/usr/bin` being to separate things in Debian 11, and `busybox --install` and `update-alternatives` not being consistent with each other. Inside a fresh `debian:11.9` container:

```bash
$ apt update && apt install -y busybox netcat-openbsd
$ ls -i /bin/busybox /bin/nc /usr/bin/nc
ls: cannot access '/usr/bin/nc': No such file or directory
15619228 /bin/busybox  15619314 /bin/nc
$ busybox --install
$ ls -i /bin/busybox /bin/nc /usr/bin/nc
15619228 /bin/busybox  15619314 /bin/nc  15619228 /usr/bin/nc
$ realpath /bin/nc
/bin/nc.openbsd
$ which nc
/usr/bin/nc
```

I think this will be solved by migrating to Debian 12, which should install [`usrmerge`](https://tracker.debian.org/pkg/usrmerge). Indeed, this is what we get:

```bash
$ apt update && apt install -y busybox netcat-openbsd
$ ls -i /bin/busybox /bin/nc /usr/bin/nc
15990847 /bin/busybox  15990922 /bin/nc  15990922 /usr/bin/nc
$ busybox --install
$ ls -i /bin/busybox /bin/nc /usr/bin/nc
15990847 /bin/busybox  15990922 /bin/nc  15990922 /usr/bin/nc
$ realpath /bin/nc
/usr/bin/nc.openbsd
$ which nc
/usr/bin/nc
```
